services:
  fairy-backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uv", "run", "fastapi", "run"]
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGODB_URI=mongodb://fairy-mongodb:27017
    restart: unless-stopped
    depends_on:
      - fairy-mongodb
  fairy-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: