apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests.yaml
- services.yaml
images:
- name: ghcr.io/kurazuuuuuu/fairy-backend-bot
  newTag: latest
- name: ghcr.io/kurazuuuuuu/fairy-backend-api
  newTag: latest
- name: ghcr.io/kurazuuuuuu/fairy-frontend
  newTag: 26e1997497936369ca2e1eb479437579f283b368
- name: ghcr.io/kurazuuuuuu/fairy-backend
  newTag: d98acc2bc8494ce65ca3598ac7716b0cc4d5f575
