apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests.yaml
images:
- name: ghcr.io/kurazuuuuuu/fairy-backend-bot
  newTag: latest
- name: ghcr.io/kurazuuuuuu/fairy-backend-api
  newTag: latest
- name: ghcr.io/kurazuuuuuu/fairy-frontend
  newTag: 74b4c6b82885275edac592089d72562ed5c055a5
- name: ghcr.io/kurazuuuuuu/fairy-backend
  newTag: d98acc2bc8494ce65ca3598ac7716b0cc4d5f575
