---
apiVersion: v1
kind: Service
metadata:
  name: fairy-backend-api-internal
  namespace: argocd-prod
spec:
  selector:
    app: fairy-backend-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fairy-backend-api-external
  namespace: argocd-prod
spec:
  selector:
    app: fairy-backend-api
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
  loadBalancerIP: 192.168.1.24
---
apiVersion: v1
kind: Service
metadata:
  name: fairy-frontend
  namespace: argocd-prod
spec:
  selector:
    app: fairy-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.1.23
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: argocd-prod
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
